[server]
host = "127.0.0.1"
port = 4221
workers = 4
backlog = 1024

[files]
root_dir = "./files"
max_file_size = 104857600
allowed_extensions = ["txt", "html", "css", "js", "json", "xml", "pdf", "jpg", "jpeg", "png", "gif"]
enable_directory_listing = false

[security]
max_request_size = 10485760
allowed_origins = ["*"]
enable_cors = true
rate_limit_requests = 1000
rate_limit_window = 60

[performance]
connection_timeout = 30
keep_alive_timeout = 5
max_connections = 10000
enable_compression = true
compression_level = 6 